pr: none
trigger:
  batch: true
  branches:
    include:
    - master
    - '*'
  paths:
    include:
      - examples/nvidia/*
      - scripts/update_kernel.sh
      - scripts/wait.sh
      - scripts/install_lis.sh
      - scripts/cuda_drivers.sh
      - scripts/check_gpu.sh
    exclude:
      - examples/nvidia/readme.md

pool: Default

variables:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  azhpc.config: examples/nvidia/config.json
  # pipeline directory
  azhpc.pipeline_dir: examples/nvidia
  # destination of scripts. Default is hpcuser@headnode:/apps
  azhpc.script_remote_dest: 'hpcadmin@jumpbox:.'

# Add the variables needed in your configuration file
# Uncomment and set values below, or leave commented and thru pipeline variables
  # azhpc.variables.location: eastus
  #azhpc.variables.vm_type: Standard_NC12s_v3
  
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
#  parameters:
#    extra_steps: ../../../examples/nvidia/test.yml
