pr: none
trigger:
  batch: true
  branches:
    include:
    - master
    - '*'
  paths:
    include:
      - examples/theia/*
      - scripts/setup-theia.sh
    exclude:
      - examples/theia/readme.md

pool: Default

variables:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  azhpc.config: examples/theia/config.json
  # pipeline directory
  azhpc.pipeline_dir: examples/theia
  # destination of scripts. Default is hpcuser@headnode:/apps
  azhpc.script_remote_dest: 'azureuser@theia:.'

# Add the variables needed in your configuration file
# Uncomment and set values below, or leave commented and thru pipeline variables
  # azhpc.variables.location: eastus
  #azhpc.variables.vm_type: Standard_NC12s_v3
  
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
#  parameters:
#    extra_steps: ../../../examples/theia/test.yml
