pr: none
trigger:
  batch: true
  branches:
    include:
    - master
    - '*'
  paths:
    include:
      - examples/beegfs/*
      - scripts/beegfspkgs.sh
      - scripts/beegfsm.sh
      - scripts/beegfssd.sh
      - scripts/beegfsmd.sh
      - scripts/beegfsc.sh
      - scripts/create_raid0.sh
      - scripts/make_filesystem.sh
    exclude:
      - examples/beegfs/readme.md

pool: Default

variables:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  azhpc.config: examples/beegfs/config.json
  # pipeline directory
  azhpc.pipeline_dir: examples/beegfs
  # destination of scripts. Default is hpcuser@headnode:/apps
  #azhpc.script_remote_dest: 'hpcadmin@jumpbox:.'

# Add the variables needed in your configuration file
# Uncomment and set values below, or leave commented and thru pipeline variables
  # azhpc.variables.location: westeurope
  azhpc.variables.compute_instances: 2

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    extra_steps: ../../../examples/beegfs/test.yml
