pr: none
trigger:
  batch: true
  branches:
    include:
    - master
    - '*'
  paths:
    include:
      - examples/glusterfs_ephemeral/*
      - scripts/glusterfs_pkgs.sh
      - scripts/glusterfs_pool.sh
      - scripts/glusterfs_vol.sh
      - scripts/glusterfs_client.sh
    exclude:
      - examples/glusterfs_ephemeral/readme.md

pool: Default

variables:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  azhpc.config: examples/glusterfs_ephemeral/config.json
  # pipeline directory
  azhpc.pipeline_dir: examples/glusterfs_ephemeral
  # destination of scripts. Default is hpcuser@headnode:/apps
  #azhpc.script_remote_dest: 'hpcadmin@headnode:.'

# Add the variables needed in your configuration file
# Uncomment and set values below, or leave commented and thru pipeline variables
  #azhpc.variables.location: southcentralus
  azhpc.variables.glusterfs_mount: '/glusterfs'
  
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    extra_steps: ../../../examples/glusterfs_ephemeral/test.yml
